config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home/about'
  root 'home#index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end
  def execute
   render json:params
  end
  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:code, :payment_method, :amount)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @categories = Category.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @categories = Category.all

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @categories = Category.all
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @categories = Category.all
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @categories = Category.all
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id, :size, :color, :price, :stock, :photo, :photo_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/about.html.erb
<style>
* {
  padding: 0;
  margin: 0;
}
.fit {
  max-width: 100%;
  max-height: 100%;
}
.center {
  display: block;
  margin: auto;
}
.wrapper {
    text-align: left;
}

.buttoncenter {
    position: absolute;
    top: 80%;
}
</style>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" language="JavaScript">
function set_body_height()
{
    var wh = $(window).height();
    $('body').attr('style', 'height:' + wh + 'px;');
}
$(document).ready(function() {
    set_body_height();
    $(window).bind('resize', function() { set_body_height(); });
});
</script>
<h1 align="center" class="font1">Minuá Jewelry Design</h1>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6" align="center">
<a href="https://www.instagram.com/minuajewelry/"><img src="<%=asset_path "90IGicon.jpg"%>" height="100" width="100"></a>
 </div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"align="center">
<a href="https://www.facebook.com/minuajewelry/"><img src="<%=asset_path "91FBicon.png"%>" height="100" width="100"></a>
</div>
</div>
<br>
<img src="<%= asset_path "11about.jpg"%>"class="center fit">

<br>

app/views/home/index.html.erb
<style>
    * {
        padding: 0;
        margin: 0;
    }
    .fit {
        max-width: 100%;
        max-height: 100%;
    }
    .center {
        display: block;
        margin: auto;
    }
    .wrapper {
        text-align: left;
    }

    .buttoncenter {
        position: absolute;
        top: 80%;
    }

</style>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" language="JavaScript">
    function set_body_height() {
        var wh = $(window).height();
        $('body').attr('style', 'height:' + wh + 'px;');
    }
    $(document).ready(function () {
        set_body_height();
        $(window).bind('resize', function () {
            set_body_height();
        });
    });
</script>
<img src="<%= asset_path "14logominua2.png"%>" class="center fit">
<p>
    <div class="wrapper">
        <button type="button" class="btn btn-default btn-lg buttoncenter" align="center"><%= link_to "Ir a la Tienda", products_path%></button>
    </div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Minua Jewelry Design</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Anonymous+Pro|Barlow+Condensed|Comfortaa|Raleway" rel="stylesheet">
        <style>
            .font1{
            font-family: 'Raleway', sans-serif;

        }
        body {
            font-family: 'Comfortaa', cursive;
        }
        p {
            font-family: 'Raleway', sans-serif;
        }
        table {
          font-family: 'Raleway', sans-serif;
        }
        </style>

    </head>
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<%= home_index_path%>"><img src="<%= asset_path "15logominuathumb.png"%>" width="110" height="50" class="img-fluid"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav nav-justified font1">
                <li>
                    <a href="<%=products_path%>">Productos<span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a href="<%=home_about_path%>">Sobre Minuá</a>
                </li>
                <% if user_signed_in? %>
                <li>
                    <a href="#">Carrito</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.email if user_signed_in?%>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Pedidos</a>
                        </li>
                        <li>
                            <a href="#">Direcciones</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="<%= destroy_user_session_path %>" data-method='delete'>Salir</a>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li>
                    <a href="<%= new_user_session_path %>">
                        Login
                    </a>
                </li>
                <li>
                    <a href="<%= new_user_registration_path %>">
                        Registro
                    </a>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->

    <body>
        <%= yield %>
    </body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, multipart: true) do |form| %>
<% if product.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %>
        prohibited this product from being saved:</h2>

    <ul>
        <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="container-fluid" class="mx-auto" align="center">
    <div class="field">
        <%= form.label :name %>
        <br>
        <%= form.text_field :name, id: :product_name %>
    </div>

    <div class="field">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, id: :product_description %>
    </div>

    <div class="field">
        <%= form.label :category_id %>
        <br>
        <% @categories.each do |c|%>
        <%=form.radio_button :category_id,c.id%><%=c.name%>
        <% end %>
    </div>

    <div class="field">
        <%= form.label :size %>
        <%= form.text_field :size, id: :product_size %>
    </div>

    <div class="field">
        <%= form.label :color %>
        <%= form.text_field :color, id: :product_color %>
    </div>

    <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, id: :product_price %>
    </div>
    <div class="field">
        <%= form.label :stock %>
        <%= form.text_field :stock, id: :product_stock %>
    </div>
    <div class="field">
        <%= form.label :photo %>
        <%= form.file_field :photo %>
        <%= form.hidden_field :photo_cache %>
        <br>
        <%= image_tag(@product.photo) if @product.photo? %>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<h1 align="center">Modificando Info del Producto</h1>

<%= render 'form', product: @product %>
<div align="center">
    <%= link_to 'Show', @product %>
    |
    <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%if current_user.try(:admin?)%>

<h3 align="center">Bienvenido
    <%=current_user.email%></h3>
<h4 align="center"><%= link_to 'Dar de Alta Nuevo Producto', new_product_path %></h4>
<%else%>
<h3 align="center">Productos Diseñados Para Tí</h3>
<% end%>

<br>

<div class="container">
  <div class="row">
  <% @products.each do |product| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
  <figure class="figure">
   <%= link_to image_tag(product.photo, class:"figure-img img-fluid rounded",class:"img-responsive",alt:"Click for info!"),product if product.photo? %>

    <div class="media-body">
  <figcaption class="figure-caption">
    <h4 class="mt-0"><%=product.name%></h4>
    <small><%=product.description%></small>
    <%if current_user.try(:admin?)%>
    <p><%= link_to 'Edit Stock or Product Info', edit_product_path(product) %></p>
    <% else %>
    <p><%= link_to 'Comprar', product%></p>
    <% end%>
    <br>
    <br>
    <br>

</figcaption>
 </figure>
 </div>
  <% end%>
  </div>
</div>
</body>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<style>
table tbody tr td {
  font-family: 'Raleway', sans-serif;
}
</style>
<div align="center">
<h3 align="center"><%=@product.name%></h3>
<h4 align="center">Información del Producto</h3>
<br>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <%= image_tag(@product.photo) if @product.photo?%>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <table width="400" height="400">
                <tbody class="font1">
                    <tr>
                        <td align="center"><%= @product.name %></td>
                        <tr>
                            <td><%= @product.description %></td>
                            <tr>
                                <td>Categoría:</td>
                                <td align="center"><%= @product.category.name %></td>
                                <tr>
                                    <td>Tamaño:</td>
                                    <td align="center"><%= @product.size %></td>
                                    <tr>
                                        <td>Color:</td>
                                        <td align="center"><%= @product.color %></td>
                                        <tr>
                                            <td>Precio:</td>
                                            <td align="center"><%= @product.price %></td>
                                            <tr>

                                                <td>Stock:</td>
                                                <td align="center"><%  if @product.stock > 0 %>
                                                    Disponible
                                                    <% else %>
                                                    No Disponible al momento
                                                    <% end%>
                                                </td>

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <br>
                            <div align:"center">
                                <%if current_user.try(:admin?)%>
                                <p><%= link_to 'Edit Stock or Product Info', edit_product_path(@product) %></p>
                            <% else %>
                                <p><%= link_to 'Comprar', products_path%></p>
                                <% end%>
                                <%= link_to 'Back', products_path %>
                            </div>
                            </div>